name: test

on:
  - push 
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - run: make test-in-docker